services:
  app:
    container_name: app
    image: app
    build:
      dockerfile: ./docker/app.Dockerfile
    ports:
      - '3000:3000'
    env_file: ./.env.production.local
    restart: always
    depends_on:
      - postgresql

  postgresql:
    container_name: postgresql
    image: postgres:16.3
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}