services:
  # app:
  #   container_name: app
  #   image: app
  #   build:
  #     # context: ./src/app
  #     dockerfile: ./docker/app.dockerfile
  #   ports:
  #     - '3000:3000'
  #   environment:
  #     - NEXT_PUBLIC_API_URL=http://localhost:4000
  #   restart: always
  #   depends_on:
  #     - postgres

  postgres:
    container_name: postgres
    image: postgres:16.3
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}